### ISSUE TITLE
Game UI

### ISSUE THREAD

**Issue by ltsLumina** [ltsLumina/NeonRivalry#19]
NOTE: Characters should be rendered IN FRONT of the UI.

- [x] Timer
- [x] Healthbars
- [ ] Character Portrait
- [x] Lives / Stocks (Just needs some art)
- [ ] Gauge (Unsure if we're going to be using a gauge to begin with)
- [x] Combo Counter
- [x] Counter text

**Comment by ltsLumina** [comment]
* Timer
* Healthbars
* Character Portrait
* Lives / Stocks
* Gauge (?: Unsure if we're using a gauge like Burst from GGST)

**Comment by Ministar200** [comment]
Passively over time gets done
