### ISSUE TITLE
Results Screen

### ISSUE THREAD

**Issue by ltsLumina** [ltsLumina/NeonRivalry#20]

**Comment by ltsLumina** [comment]
As in the screen that shows the results of the match.
![image](https://github.com/ltsLumina/FightingGame/assets/119983088/4b81d4c8-c658-4d15-a4fc-573bf6718094)

**Comment by Ministar200** [comment]
Sliders are working but the system needs to be remade and refined later on once the fighting system is fully complete and we can work on it easier and more effectively.

**Comment by Ministar200** [comment]
They are now animated and fill up to the desired value rather than go all at once

**Comment by Ministar200** [comment]
Leaving this on hold, i want to have a counter for the ammount moves blocked/hit etc which impact the sliders on the result screen.
