### ISSUE TITLE
Main Menu Screen

### ISSUE THREAD

**Issue by ltsLumina** [ltsLumina/NeonRivalry#3]

**Comment by ltsLumina** [comment]
Title Screen
   - Fade in audio quickly as to not startle player.
   - Menu Buttons
     - Play
        > Character Select
            - Select character > Choose colour > Confirm Ready.
            - Once both players ready, fade to black and load game scene.
     - Characters (overview)
     - Quit
     - Settings
        - Audio
        - Controls
        - Graphics

**Comment by Ministar200** [comment]
Grafik saknas
