### ISSUE TITLE
Character Animations

### ISSUE THREAD

**Issue by ltsLumina** [ltsLumina/NeonRivalry#63]
## Prio-Lista

- [x] Idle
- [x] Walk
- [ ] Jump
- [x] Crouch

## Animations
- [x] Idle
- [x] Walk
- [x] Jump
- [x] Hitstun (player gets hit)
- [ ] Hitstun (player gets sweeped off their feet)
- [x] Blocking (1 frame)
- [x] Crouch

### Punch
_Note: Forward and Back are the same animation._
- [x] Neutral Punch
- [x] Forward/Back Punch

### Slash (Main)
- [ ] Slash
- [ ] Forward/Back Slash 
- [x] Jump Down Slash
- [x] Low Slash (Works as leg sweep)

### Unique
- [ ] Unique Attack

## Airborne Animations
_Note: All attack buttons perform the same airborne attack animation._
- [x] Airborne Attack

## Stretch Goal (if we have extra time to add stuff)
- [ ] Fall
- [ ] Landing
- [ ] Grab/Throw
- [ ] Dash

**Comment by sharonchaos** [comment]
bullshit
